### ISSUE TITLE
Feature Request: Default bun packages

### ISSUE THREAD

**Issue by aarvay** [cometkim/asdf-bun#14]
Like how asdf-nodejs can automatically install a set of default packages right after installing node ([ref](https://github.com/asdf-vm/asdf-nodejs#default-npm-packages)), we should have the ability to specify default bun packages

**Comment by cometkim** [comment]
Is that feature for global? I'd recommend using `bunx` then

**Comment by willian** [comment]
I also agree with @aarvay on this feature request. Not only `asdf-node` follows this approach, `asdf-ruby` (`.default-gems` file), `asdf-python` (`.default-python-packages` file), and many others also follow this approach.
The idea is to have some global packages installed automatically as soon as a new version of Bun is installed via `asdf install ...`. This is useful for keeping the environment consistency no matter what version of Bun we're running.

**Comment by aarvay** [comment]
@cometkim yes the feature request is for global. bunx is for executing a package binary.

Apart from having parity with other plugins in the ecosystem like @willian mentioned, another nice thing about having this feature would be that, this file (.default-bun-packages) can live in your dotfiles repo and be part of the init script (for new machine setup)

**Comment by cometkim** [comment]
I'm not sure if I understood it correctly.

There is no reason to reinstall a global package due to a bun version change. Also, naive reinstallation may be a potential security risk because it does not respect package locks.

Moving global packages to a new machine makes sense to me. But why do we need a new format like `.default-bun-packages` instead of migrating `$HOME/.bun/install/global/{package.json, bun.lockb}` files already exist?

I think running `bun install --cwd ~/.bun/install/global` after installation is better solution.

**Comment by cometkim** [comment]
Ok, I figured out some problems with global installs that I wanna fix before adding this feature.

The first problem with bun install is that installs all the transitive dependencies binaries as well, which is not good for `PATH`. Second is users have to manually configure the `PATH`.

I will fix problems by adding shim for `bun install` command like `asdf-nodejs` does.

**Comment by cometkim** [comment]
Bun has the problem of not being well suited to handle global installations (See https://github.com/oven-sh/bun/issues/6928)

I could override the behavior like the asdf-nodejs plugin does for npm, but I believe that's not the correct move. I would not recommend managing global installations via Bun until this is discussed upstream.
